In [353]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [354]:
cars_data=pd.read_csv('Cardetails.csv')

In [355]:
cars_data.head(1)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0

In [356]:
cars_data.drop(columns=['torque'],inplace=True)

In [357]:
cars_data.head(1)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,5.0

In [358]:
cars_data.shape

(8128, 12)

Preprocessing

Null Check

In [359]:
cars_data.isnull().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
seats            221
dtype: int64

In [360]:
cars_data.dropna(inplace=True)

In [361]:
cars_data.shape

(7907, 12)

Duplicate check

In [362]:
cars_data.duplicated().sum()

1189

In [363]:
cars_data.drop_duplicates(inplace=True)

In [364]:
cars_data.shape

(6718, 12)

In [365]:
cars_data.head(1)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,5.0

In [366]:
cars_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6718 entries, 0 to 8125
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           6718 non-null   object
 1   year           6718 non-null   int64
 2   selling_price  6718 non-null   int64
 3   km_driven      6718 non-null   int64
 4   fuel           6718 non-null   object
 5   seller_type    6718 non-null   object
 6   transmission   6718 non-null   object
 7   owner          6718 non-null   object
 8   mileage        6718 non-null   object
 9   engine         6718 non-null   object
 10  max_power      6718 non-null   object
 11  seats          6718 non-null   float64
dtypes: float64(1), int64(3), object(8)
memory usage: 682.3+ KB

Data Analysis

Types of Data

In [367]:
for col in cars_data.columns:
    print('Unique Values of column: ',col)
    print(cars_data[col].unique())
    print('************************')
    print('Sum:   ',cars_data[col].unique().sum())
    print('-----------------------------------------------------------------------------------------------------')

Unique Values of column:  name
['Maruti Swift Dzire VDI' 'Skoda Rapid 1.5 TDI Ambition'
 'Honda City 2017-2020 EXi' ... 'Tata Nexon 1.5 Revotorq XT'
 'Ford Freestyle Titanium Plus Diesel BSIV'
 'Toyota Innova 2.5 GX (Diesel) 8 Seater BS IV']
************************

In [368]:
cars_data['Brand']=cars_data['name'].str.split(' ').str[0]

In [369]:
cars_data['Brand'].unique()

array(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Datsun', 'Jeep', 'Mercedes-Benz',
       'Mitsubishi', 'Audi', 'Volkswagen', 'BMW', 'Nissan', 'Lexus',
       'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo', 'Kia', 'Fiat', 'Force',
       'Ambassador', 'Ashok', 'Isuzu', 'Opel'], dtype=object)

In [370]:
cars_data.head(1)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats,Brand
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,5.0,Maruti

In [371]:
cars_data['mileage']=cars_data['mileage'].str.split(' ').str[0]
cars_data['max_power'] = cars_data['max_power'].str.split(' ').str[0].str.strip()
cars_data['max_power'] = cars_data['max_power'].replace('', 0).astype(float)
cars_data['engine']=cars_data['engine'].str.split(' ').str[0]

In [372]:
cars_data.head(1)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats,Brand
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4,1248,74.0,5.0,Maruti

In [373]:
cars_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6718 entries, 0 to 8125
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           6718 non-null   object
 1   year           6718 non-null   int64
 2   selling_price  6718 non-null   int64
 3   km_driven      6718 non-null   int64
 4   fuel           6718 non-null   object
 5   seller_type    6718 non-null   object
 6   transmission   6718 non-null   object
 7   owner          6718 non-null   object
 8   mileage        6718 non-null   object
 9   engine         6718 non-null   object
 10  max_power      6718 non-null   float64
 11  seats          6718 non-null   float64
 12  Brand          6718 non-null   object
dtypes: float64(2), int64(3), object(8)
memory usage: 734.8+ KB

In [374]:
cars_data['mileage']=cars_data['mileage'].astype(float)

In [375]:
cars_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6718 entries, 0 to 8125
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           6718 non-null   object
 1   year           6718 non-null   int64
 2   selling_price  6718 non-null   int64
 3   km_driven      6718 non-null   int64
 4   fuel           6718 non-null   object
 5   seller_type    6718 non-null   object
 6   transmission   6718 non-null   object
 7   owner          6718 non-null   object
 8   mileage        6718 non-null   float64
 9   engine         6718 non-null   object
 10  max_power      6718 non-null   float64
 11  seats          6718 non-null   float64
 12  Brand          6718 non-null   object
dtypes: float64(3), int64(3), object(7)
memory usage: 734.8+ KB

In [376]:
for col in cars_data.columns:
    print('Unique Values of column: ',col)
    print(cars_data[col].unique())
    print('************************')
    print('Sum:   ',cars_data[col].unique().sum())
    print('-----------------------------------------------------------------------------------------------------')

Unique Values of column:  name
['Maruti Swift Dzire VDI' 'Skoda Rapid 1.5 TDI Ambition'
 'Honda City 2017-2020 EXi' ... 'Tata Nexon 1.5 Revotorq XT'
 'Ford Freestyle Titanium Plus Diesel BSIV'
 'Toyota Innova 2.5 GX (Diesel) 8 Seater BS IV']
************************

In [377]:
cars_data['Brand'].replace(
    ['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault', 'Mahindra',
     'Tata', 'Chevrolet', 'Datsun', 'Jeep', 'Mercedes-Benz', 'Mitsubishi', 'Audi',
     'Volkswagen', 'BMW', 'Nissan', 'Lexus', 'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo',
     'Kia', 'Fiat', 'Force', 'Ambassador', 'Ashok', 'Isuzu', 'Opel'],
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
    inplace=True
)

C:\Users\chara\AppData\Local\Temp\ipykernel_18912\226654401.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cars_data['Brand'].replace(
C:\Users\chara\AppData\Local\Temp\ipykernel_18912\226654401.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  cars_data['Brand'].replace(

In [378]:
cars_data['transmission'].unique()

array(['Manual', 'Automatic'], dtype=object)

In [379]:
cars_data['transmission'].replace(['Manual', 'Automatic'], [1, 2], inplace=True)

C:\Users\chara\AppData\Local\Temp\ipykernel_18912\1698677116.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cars_data['transmission'].replace(['Manual', 'Automatic'], [1, 2], inplace=True)
C:\Users\chara\AppData\Local\Temp\ipykernel_18912\1698677116.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  cars_data['transmission'].replace(['Manual', 'Automatic'], [1, 2], inplace=True)

In [380]:
cars_data['seller_type'].unique()

array(['Individual', 'Dealer', 'Trustmark Dealer'], dtype=object)

In [381]:
cars_data['seller_type'].replace(['Individual', 'Dealer', 'Trustmark Dealer'], [1, 2, 3], inplace=True)

C:\Users\chara\AppData\Local\Temp\ipykernel_18912\748609640.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cars_data['seller_type'].replace(['Individual', 'Dealer', 'Trustmark Dealer'], [1, 2, 3], inplace=True)
C:\Users\chara\AppData\Local\Temp\ipykernel_18912\748609640.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  cars_data['seller_type'].replace(['Individual', 'Dealer', 'Trustmark Dealer'], [1, 2, 3], inplace=True)

In [382]:
cars_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6718 entries, 0 to 8125
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           6718 non-null   object
 1   year           6718 non-null   int64
 2   selling_price  6718 non-null   int64
 3   km_driven      6718 non-null   int64
 4   fuel           6718 non-null   object
 5   seller_type    6718 non-null   int64
 6   transmission   6718 non-null   int64
 7   owner          6718 non-null   object
 8   mileage        6718 non-null   float64
 9   engine         6718 non-null   object
 10  max_power      6718 non-null   float64
 11  seats          6718 non-null   float64
 12  Brand          6718 non-null   int64
dtypes: float64(3), int64(6), object(4)
memory usage: 734.8+ KB

In [383]:
cars_data['fuel'].unique()

array(['Diesel', 'Petrol', 'LPG', 'CNG'], dtype=object)

In [384]:
cars_data['fuel'].replace(['Diesel', 'Petrol', 'LPG', 'CNG'], [1, 2, 3, 4], inplace=True)

C:\Users\chara\AppData\Local\Temp\ipykernel_18912\2655382713.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cars_data['fuel'].replace(['Diesel', 'Petrol', 'LPG', 'CNG'], [1, 2, 3, 4], inplace=True)
C:\Users\chara\AppData\Local\Temp\ipykernel_18912\2655382713.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  cars_data['fuel'].replace(['Diesel', 'Petrol', 'LPG', 'CNG'], [1, 2, 3, 4], inplace=True)

In [385]:
cars_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6718 entries, 0 to 8125
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           6718 non-null   object
 1   year           6718 non-null   int64
 2   selling_price  6718 non-null   int64
 3   km_driven      6718 non-null   int64
 4   fuel           6718 non-null   int64
 5   seller_type    6718 non-null   int64
 6   transmission   6718 non-null   int64
 7   owner          6718 non-null   object
 8   mileage        6718 non-null   float64
 9   engine         6718 non-null   object
 10  max_power      6718 non-null   float64
 11  seats          6718 non-null   float64
 12  Brand          6718 non-null   int64
dtypes: float64(3), int64(7), object(3)
memory usage: 734.8+ KB

In [386]:
cars_data.head(1)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats,Brand
0,Maruti Swift Dzire VDI,2014,450000,145500,1,1,1,First Owner,23.4,1248,74.0,5.0,1

In [387]:
cars_data.reset_index(inplace=True,drop=True)

In [388]:
cars_data

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats,Brand
0,Maruti Swift Dzire VDI,2014,450000,145500,1,1,1,First Owner,23.40,1248,74.00,5.0,1
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,1,1,1,Second Owner,21.14,1498,103.52,5.0,2
2,Honda City 2017-2020 EXi,2006,158000,140000,2,1,1,Third Owner,17.70,1497,78.00,5.0,3
3,Hyundai i20 Sportz Diesel,2010,225000,127000,1,1,1,First Owner,23.00,1396,90.00,5.0,4
4,Maruti Swift VXI BSIII,2007,130000,120000,2,1,1,First Owner,16.10,1298,88.20,5.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6713,Maruti Wagon R VXI BS IV with ABS,2013,260000,50000,2,1,1,Second Owner,18.90,998,67.10,5.0,1
6714,Hyundai i20 Magna 1.4 CRDi,2014,475000,80000,1,1,1,Second Owner,22.54,1396,88.73,5.0,4
6715,Hyundai i20 Magna,2013,320000,110000,2,1,1,First Owner,18.50,1197,82.85,5.0,4
6716,Hyundai Verna CRDi SX,2007,135000,119000,1,1,1,Fourth & Above Owner,16.80,1493,110.00,5.0,4
6717,Maruti Swift Dzire ZDi,2009,382000,120000,1,1,1,First Owner,19.30,1248,73.90,5.0,1

In [389]:
cars_data['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth & Above Owner', 'Test Drive Car'], dtype=object)

In [390]:
cars_data['owner'].replace(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth & Above Owner', 'Test Drive Car'],[1,2,3,4,5],inplace=True)

C:\Users\chara\AppData\Local\Temp\ipykernel_18912\416776316.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cars_data['owner'].replace(['First Owner', 'Second Owner', 'Third Owner',
C:\Users\chara\AppData\Local\Temp\ipykernel_18912\416776316.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  cars_data['owner'].replace(['First Owner', 'Second Owner', 'Third Owner',

In [391]:
cars_data.head(1)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats,Brand
0,Maruti Swift Dzire VDI,2014,450000,145500,1,1,1,1,23.4,1248,74.0,5.0,1

In [392]:
cars_data['name']=cars_data['Brand']
cars_data.drop(columns=['Brand'],inplace=True)

In [393]:
cars_data.head(1)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
0,1,2014,450000,145500,1,1,1,1,23.4,1248,74.0,5.0

In [394]:
input_data=cars_data.drop(columns=['selling_price'])
output_data=cars_data['selling_price']

In [395]:
x_train,x_test,y_train,y_shape=train_test_split(input_data,output_data,test_size=0.2)

Model Creation

In [396]:
model=LinearRegression()

Train Model

In [397]:
model.fit(x_train,y_train)

LinearRegression()

In [398]:
predict=model.predict(x_test)

In [399]:
predict

array([1145323.27147487, -218303.8230157 ,  438265.43411621, ...,
       -125435.88217337,  514578.69516456,  353573.4463653 ])

In [400]:
x_train.head(1)

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
2480,1,2015,40000,1,1,1,1,24.52,1248,88.5,7.0

In [410]:
input_data_model=pd.DataFrame(
    [[5,2015,12000,1,1,1,1,12.99,2494.0,100.6,5.0]],columns=['name','year','km_driven','fuel','seller_type','transmission','owner','mileage','engine','max_power','seats'] )

In [411]:
input_data_model

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
0,5,2015,12000,1,1,1,1,12.99,2494.0,100.6,5.0

In [412]:
model.predict(input_data_model)

array([747791.59482059])

Save Model

In [413]:
import pickle as pk

In [414]:
pk.dump(model,open('model.pkl','wb'))